title: "The Future of Money and HCI"
description: "CHI 2025 Workshop | Yokohama, Japan"
baseurl: /
url: chi2025-money.github.io

permalink: pretty
remote-theme: "piazzai/jekyll-nagymaros"

home: /
copyright: 
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

google_analytics:
  id: "G-X8HGV5RMNG"
